version: '3'
services:

  web:
    build: ./nginx
#    links:
#      - notebook-web-app
    ports:
      - "7875:80"
    volumes:
      - "./nginx/ngnix.conf:/etc/nginx/conf.d/default.conf"

  notebook-api:
#    links:
#      - db
    build:
      context: ./notebook-api


#  notebook-web-app:
#    links:
#      - notebook-api-app
#    build:
#      context: ./notebook-web-app
#    volumes:

#    entrypoint: ["/start-web"]