version: '3'
services:

  web:
    build: ./nginx
    links:
      - notebook-web
    ports:
      - "7875:80"
    volumes:
      - "./nginx/ngnix.conf:/etc/nginx/conf.d/default.conf"

  notebook-api:
#    links:
#      - db
    build:
      context: ./notebook-api


  notebook-web:
    links:
      - notebook-api
    build:
      context: ./notebook-web
    volumes:
      - "./notebook-web/src:/app/src"
      - "./notebook-web/public:/app/public"